evaluation_output: ../results/test.csv
main_metric: neg_mean_squared_error
main_metric_mode: max
scoring_metrics:
- spearman
- r2_score
- mean_squared_error
- pearson
model_description: test
model_type: RandomForest
opt_hyperparams_path: settings_files/ml/test_ml.pkl
test_cnv_filepath: null
test_drugA_adj_filepath: null
test_drugA_atom_feat_filepath: null
test_drugA_filepath: ../data/test/test_ECFP4_drugA.npy
test_drugB_adj_filepath: null
test_drugB_atom_feat_filepath: null
test_drugB_filepath: ../data/test/test_ECFP4_drugB.npy
test_expr_filepath: ../data/test/expr_scaled_test.npy
test_mut_filepath: null
test_response_filepath: ../data/test/split_data_test.csv.gz
train_cnv_filepath: null
train_drugA_adj_filepath: null
train_drugA_atom_feat_filepath: null
train_drugA_filepath: ../data/test/train_ECFP4_drugA.npy
train_drugB_adj_filepath: null
train_drugB_atom_feat_filepath: null
train_drugB_filepath: ../data/test/train_ECFP4_drugB.npy
train_expr_filepath: ../data/test/expr_scaled_train.npy
train_mut_filepath: null
train_response_filepath: ../data/test/split_data_train.csv.gz
val_cnv_filepath: null
val_drugA_adj_filepath: null
val_drugA_atom_feat_filepath: null
val_drugA_filepath: ../data/test/val_ECFP4_drugA.npy
val_drugB_adj_filepath: null
val_drugB_atom_feat_filepath: null
val_drugB_filepath: ../data/test/val_ECFP4_drugB.npy
val_expr_filepath: ../data/test/expr_scaled_val.npy
val_mut_filepath: null
val_response_filepath: ../data/test/split_data_val.csv.gz
