batch_size: 64
epochs: 500
evaluation_output: ../results/dl_model_evaluation_results_cellminercdb_recalculated_scores.csv
gpu_to_use:
- 6
main_metric: val_mean_squared_error
main_metric_mode: min
model_description: cell line (one-hot) + drugs (one-hot)
model_type: expr_drug_dense_model
opt_hyperparams_path: settings_files/onehot_cells_onehot_drugs_hyperparam_space_redo.pkl
test_cnv_filepath: null
test_drugA_adj_filepath: null
test_drugA_atom_feat_filepath: null
test_drugA_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugA_NSCs_test.npy
test_drugB_adj_filepath: null
test_drugB_atom_feat_filepath: null
test_drugB_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugB_NSCs_test.npy
test_expr_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_cell_line_names_test.npy
test_mut_filepath: null
test_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_test.csv.gz
train_cnv_filepath: null
train_drugA_adj_filepath: null
train_drugA_atom_feat_filepath: null
train_drugA_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugA_NSCs_train.npy
train_drugB_adj_filepath: null
train_drugB_atom_feat_filepath: null
train_drugB_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugB_NSCs_train.npy
train_expr_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_cell_line_names_train.npy
train_mut_filepath: null
train_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_train.csv.gz
use_data_generators: true
val_cnv_filepath: null
val_drugA_adj_filepath: null
val_drugA_atom_feat_filepath: null
val_drugA_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugA_NSCs_val.npy
val_drugB_adj_filepath: null
val_drugB_atom_feat_filepath: null
val_drugB_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_drugB_NSCs_val.npy
val_expr_filepath: ../data/nci_almanac_preprocessed/onehot/onehot_cell_line_names_val.npy
val_mut_filepath: null
val_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_val.csv.gz