batch_size: 64
epochs: 500
evaluation_output: ../results/model_evaluation_results_cellminercdb.csv
gpu_to_use:
- 3
main_metric: val_mean_squared_error
main_metric_mode: min
model_description: expr (target + landmark genes, dense, MinMaxScaler) + drug (ECFP4, Dense)
model_type: expr_drug_dense_model
opt_hyperparams_path: settings_files/expr_target_genes_landmark_drug_ecpf4_hyperparam_space.pkl
test_cnv_filepath: null
test_drugA_adj_filepath: null
test_drugA_atom_feat_filepath: null
test_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_test.npy
test_drugB_adj_filepath: null
test_drugB_atom_feat_filepath: null
test_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_test.npy
test_expr_filepath: ../data/nci_almanac_preprocessed/omics/split/merged_rnaseq_fpkm_target_landmark_genes_reduced_test.npy
test_mut_filepath: null
test_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_test.csv.gz
train_cnv_filepath: null
train_drugA_adj_filepath: null
train_drugA_atom_feat_filepath: null
train_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_train.npy
train_drugB_adj_filepath: null
train_drugB_atom_feat_filepath: null
train_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_train.npy
train_expr_filepath: ../data/nci_almanac_preprocessed/omics/split/merged_rnaseq_fpkm_target_landmark_genes_reduced_train.npy
train_mut_filepath: null
train_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_train.csv.gz
use_data_generators: true
val_cnv_filepath: null
val_drugA_adj_filepath: null
val_drugA_atom_feat_filepath: null
val_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_val.npy
val_drugB_adj_filepath: null
val_drugB_atom_feat_filepath: null
val_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_val.npy
val_expr_filepath: ../data/nci_almanac_preprocessed/omics/split/merged_rnaseq_fpkm_target_landmark_genes_reduced_val.npy
val_mut_filepath: null
val_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_val.csv.gz
