batch_size: 32
epochs: 500
evaluation_output: ../results/model_evaluation_results_cellminercdb.csv
gpu_to_use:
- 0
- 1
main_metric: val_mean_squared_error
main_metric_mode: min
model_description: one-hot encoded cell line names + drug (ECFP4, 1024, dense)
model_type: expr_drug_dense_model
opt_hyperparams_path: settings_files/onehot_cells_hyperparam_space.pkl
train_final_model: false
full_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples.csv
full_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_full.npy
full_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_full.npy
full_expr_filepath: ../data/nci_almanac_preprocessed/onehot_encoded/onehot_cell_line_names_full.npy
full_mut_filepath: null
full_cnv_filepath: null
train_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_train.csv.gz
train_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_train.npy
train_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_train.npy
train_expr_filepath: ../data/nci_almanac_preprocessed/onehot_encoded/onehot_cell_line_names_train.npy
train_mut_filepath: null
train_cnv_filepath: null
val_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_val.csv.gz
val_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_val.npy
val_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_val.npy
val_expr_filepath: ../data/nci_almanac_preprocessed/onehot_encoded/onehot_cell_line_names_val.npy
val_mut_filepath: null
val_cnv_filepath: null
test_response_filepath: ../data/nci_almanac_preprocessed/response/almanac_cellminercdb_with_preprocessed_smiles_no_duplicate_triples_test.csv.gz
test_drugA_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugA_test.npy
test_drugB_filepath: ../data/nci_almanac_preprocessed/drugs/ECFP4_1024_drugB_test.npy
test_expr_filepath: ../data/nci_almanac_preprocessed/onehot_encoded/onehot_cell_line_names_test.npy
test_mut_filepath: null
test_cnv_filepath: null
use_data_generators: true